# Generated by Django 5.0.3 on 2024-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='price',
            field=models.CharField(default='$50000', max_length=200),
            preserve_default=False,
        ),
    ]
