# Generated by Django 5.0.3 on 2024-03-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='google_plus_link',
            new_name='instagram_link',
        ),
    ]
