# Generated by Django 5.0.3 on 2024-03-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_teams_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['created_date'], 'verbose_name_plural': 'Teams'},
        ),
    ]
