# Generated by Django 5.0.3 on 2024-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=200),
        ),
    ]
