# Generated by Django 5.0.3 on 2024-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_transmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='reg_car_number',
            new_name='car_reg_number',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='transmission',
            new_name='transmission_type',
        ),
        migrations.AlterField(
            model_name='cars',
            name='doors',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric')], max_length=200),
        ),
        migrations.AlterField(
            model_name='cars',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
