# Generated by Django 5.0.3 on 2024-03-21 11:42

import ckeditor.fields
import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_reg_car_number_cars_car_reg_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Alarm System', 'Alarm System'), ('Anti-lock Braking System (ABS)', 'Anti-lock Braking System (ABS)'), ('Audio Interface', 'Audio Interface'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Central Locking System', 'Central Locking System'), ('Cruise Control', 'Cruise Control'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Seat Heating', 'Seat Heating'), ('Wind Deflector', 'Wind Deflector')], max_length=200),
        ),
        migrations.AlterField(
            model_name='cars',
            name='transmission_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=200),
        ),
    ]
