# Generated by Django 5.0.3 on 2024-03-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_cars_description_alter_cars_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='transmission_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=200),
        ),
    ]
