# Generated by Django 5.0.3 on 2024-03-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_cars_doors_alter_cars_features_alter_cars_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='doors',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
