# Generated by Django 5.0.3 on 2024-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_cars_doors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['created_date'], 'verbose_name_plural': 'Cars'},
        ),
        migrations.AddField(
            model_name='cars',
            name='drivetrain',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
