# Generated by Django 5.0.3 on 2024-03-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_cars_options_cars_drivetrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='drivetrain',
            field=models.CharField(choices=[('Front Wheel Drive (FWD)', 'Front Wheel Drive (FWD)'), ('Rear Wheel Drive (RWD)', 'Rear Wheel Drive (RWD)'), ('All Wheel Drive (AWD)', 'All Wheel Drive (AWD)'), ('4 Wheel Drive (4WD)', '4 Wheel Drive (4WD)')], max_length=500),
        ),
    ]
