# Generated by Django 5.0.3 on 2024-03-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_cars_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_brand',
            field=models.CharField(default='Ford', max_length=200),
        ),
    ]
