# Generated by Django 5.0.3 on 2024-03-29 06:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_cars_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, null=True, populate_from='car_title', unique=True),
        ),
    ]
